### ISSUE TITLE
修改快捷键就出这个错误

### ISSUE THREAD

**Issue by breezeit** [wyagd001/MyScript#1]
![snipaste_2018-11-20_11-32-44](https://user-images.githubusercontent.com/17754387/48749967-0cf01b80-ecb8-11e8-931c-daf39d7f0483.png)
取消了几个默认快捷键，就弹出这个，然后脚本全部自动退出了。
sqlite3.dll也在呢，并没有不存在。

**Comment by wyagd001** [comment]
没遇到过，不过你可以把你修改的配置文件快捷键部分贴出来看看

**Comment by breezeit** [comment]
基本上什么都没法改。

我自己有candy在用的，设定的快捷键不一样(f4)。所以想把你这个脚本里的candy给去掉，就把前面的√去了，然后点“确定”，就报错了。然后试试，不去掉√改脚本里的candy的快捷方式为其他比如^f3(^f1我已经分配过自己经常用的everything了)，“确定”后，也同样报错。总体上的感觉是“快捷键”什么都不能动，一动就报错，明明sqlite3.dll一直都在，也没丢失。

**Comment by wyagd001** [comment]
再次测试了下，我的电脑中可以改快捷键。只有 Sqlite3.dll 文件不存在时，才会弹出你描述的错误对话框。
昨天脚本已经修改了，当 Sqlite3.dll 不存在时，不再退出脚本。

**Comment by wyagd001** [comment]
你的电脑是不是64位的啊，dll 版本是32位的。

**Comment by breezeit** [comment]
是的。win10,64位，1809版本。

**Comment by wyagd001** [comment]
我的系统是32位的，所有dll也是32位适配的，脚本代码也是32位适配的，所以64位系统需要下载64位的dll文件，使用64位的autohotkey，可能需要修改代码。
选项→其他→取消勾选剪贴板历史，不使用该dll。
